# Generated by Django 5.2.8 on 2025-11-30 12:00

from django.db import migrations

def update_site_domain(apps, schema_editor):
    """
    Updates the default site domain to use the production server's IP address.
    """
    Site = apps.get_model('sites', 'Site')
    default_site = Site.objects.get(pk=1)
    default_site.domain = '51.20.86.40'
    default_site.name = 'eCommerce Production'
    default_site.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        # Add a dependency on the sites app's initial migration
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_site_domain),
    ]
